name: codeflux_mobile
description: CODEFLUX Officer field application.
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  flutter_secure_storage: ^11.2.0
  http: ^1.6.0
  image_picker: ^1.2.3
  path: ^1.9.1
  path_provider: ^2.1.6
  sqflite: ^2.4.2+1
  sqflite_common: ^2.5.8
  uuid: ^4.6.0

flutter:
  uses-material-design: true
